### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by eaedk** [ikoghoemmanuell/Machine-Learning-API-using-FastAPI#1]
in this [section](https://github.com/ikoghoemmanuell/Sepsis-Prediction-with-ML-and-FastAPI#run-fastapi) adapt the command to your project.

in this [section](https://github.com/ikoghoemmanuell/Sepsis-Prediction-with-ML-and-FastAPI#setup) the second command should be like the windows one

**Comment by ikoghoemmanuell** [comment]
All done
