### ISSUE TITLE
Observation

### ISSUE THREAD

**Issue by eaedk** [ikoghoemmanuell/Machine-Learning-API-using-FastAPI#2]
You said "Since Plasma_Glucose and Patient_age are highly correlated, we will remove Plasma_Glucose" the when I check the correlation matrix I can't agree with you. https://www.verywellmind.com/what-is-correlation-2794986

**Comment by ikoghoemmanuell** [comment]
I used scatter plot to examine the non-linear relationship between Plasma_Glucose & Patient_Age

Then I oberved that the data points were widely dispersed. This led me to believe that they had a weak relationship, or no relationship at all. 

Therefore, I decided to keep both variables. My f1 score after fine-tuning increased from 0.85 to 0.86 as a result. Thanks!
